name: Push Release NuGet
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Push Master Builds To NuGet
      run: >
        dotnet
        nuget
        push
        --api-key ${{ secrets.NUGET_API_KEY }}
        --Source https://api.nuget.org/v3/index.json
        ./artifacts/*.nupkg
      if: endsWith(github.ref, 'real-master')